name: lint Go Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: "false"
        go-version: 1.16

    - name: Install dependencies
      run: |
        go version
        cd src && go get -u golang.org/x/lint/golint
      
    - name: Run vet & lint
      run: |
        cd src && go vet .
        golint .
